//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnThucTap.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ThucTap_DoAnEntities : DbContext
    {
        public ThucTap_DoAnEntities()
            : base("name=ThucTap_DoAnEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TBL_ChiTietPhieuThu> TBL_ChiTietPhieuThu { get; set; }
        public DbSet<TBL_KhoanThuMonHoc> TBL_KhoanThuMonHoc { get; set; }
        public DbSet<TBL_PhieuThu> TBL_PhieuThu { get; set; }
        public DbSet<TBL_SinhVien> TBL_SinhVien { get; set; }
        public DbSet<TBL_ThanhToan> TBL_ThanhToan { get; set; }
        public DbSet<TBL_DangKy> TBL_DangKy { get; set; }
    
        [EdmFunction("ThucTap_DoAnEntities", "GetDangKySinhVien")]
        public virtual IQueryable<GetDangKySinhVien_Result> GetDangKySinhVien(string mssv)
        {
            var mssvParameter = mssv != null ?
                new ObjectParameter("mssv", mssv) :
                new ObjectParameter("mssv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetDangKySinhVien_Result>("[ThucTap_DoAnEntities].[GetDangKySinhVien](@mssv)", mssvParameter);
        }
    
        [EdmFunction("ThucTap_DoAnEntities", "GetTBLSoPhieu_CT")]
        public virtual IQueryable<GetTBLSoPhieu_CT_Result> GetTBLSoPhieu_CT(string soPhieu)
        {
            var soPhieuParameter = soPhieu != null ?
                new ObjectParameter("SoPhieu", soPhieu) :
                new ObjectParameter("SoPhieu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetTBLSoPhieu_CT_Result>("[ThucTap_DoAnEntities].[GetTBLSoPhieu_CT](@SoPhieu)", soPhieuParameter);
        }
    
        public virtual ObjectResult<sp_ChiTietPhieuThu_Result> sp_ChiTietPhieuThu(string soPhieu)
        {
            var soPhieuParameter = soPhieu != null ?
                new ObjectParameter("soPhieu", soPhieu) :
                new ObjectParameter("soPhieu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ChiTietPhieuThu_Result>("sp_ChiTietPhieuThu", soPhieuParameter);
        }
    
        public virtual ObjectResult<sp_ChiTietPhieuThuIn_PDF_Result> sp_ChiTietPhieuThuIn_PDF(string soPhieu)
        {
            var soPhieuParameter = soPhieu != null ?
                new ObjectParameter("soPhieu", soPhieu) :
                new ObjectParameter("soPhieu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ChiTietPhieuThuIn_PDF_Result>("sp_ChiTietPhieuThuIn_PDF", soPhieuParameter);
        }
    
        public virtual ObjectResult<sp_DanhSachQuanLyThu_Result> sp_DanhSachQuanLyThu(string ptrangthai)
        {
            var ptrangthaiParameter = ptrangthai != null ?
                new ObjectParameter("ptrangthai", ptrangthai) :
                new ObjectParameter("ptrangthai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DanhSachQuanLyThu_Result>("sp_DanhSachQuanLyThu", ptrangthaiParameter);
        }
    
        public virtual int sp_Delete_KhoanThu(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Delete_KhoanThu", idParameter);
        }
    
        public virtual int sp_DeletePhieuThu(string soPhieu)
        {
            var soPhieuParameter = soPhieu != null ?
                new ObjectParameter("soPhieu", soPhieu) :
                new ObjectParameter("soPhieu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeletePhieuThu", soPhieuParameter);
        }
    
        public virtual ObjectResult<sp_GetAllPhieuThu_Result> sp_GetAllPhieuThu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAllPhieuThu_Result>("sp_GetAllPhieuThu");
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_GetDonGiaByMaMH(string mamh)
        {
            var mamhParameter = mamh != null ?
                new ObjectParameter("mamh", mamh) :
                new ObjectParameter("mamh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_GetDonGiaByMaMH", mamhParameter);
        }
    
        public virtual ObjectResult<string> sp_GetEmailSinhVien(string mssv)
        {
            var mssvParameter = mssv != null ?
                new ObjectParameter("mssv", mssv) :
                new ObjectParameter("mssv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_GetEmailSinhVien", mssvParameter);
        }
    
        public virtual ObjectResult<sp_GetPhieuThuByAll_Result> sp_GetPhieuThuByAll(string masv, string sophieu, Nullable<System.DateTime> ngaybatdau, Nullable<System.DateTime> ngayketthuc)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            var sophieuParameter = sophieu != null ?
                new ObjectParameter("sophieu", sophieu) :
                new ObjectParameter("sophieu", typeof(string));
    
            var ngaybatdauParameter = ngaybatdau.HasValue ?
                new ObjectParameter("ngaybatdau", ngaybatdau) :
                new ObjectParameter("ngaybatdau", typeof(System.DateTime));
    
            var ngayketthucParameter = ngayketthuc.HasValue ?
                new ObjectParameter("ngayketthuc", ngayketthuc) :
                new ObjectParameter("ngayketthuc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPhieuThuByAll_Result>("sp_GetPhieuThuByAll", masvParameter, sophieuParameter, ngaybatdauParameter, ngayketthucParameter);
        }
    
        public virtual ObjectResult<sp_GetPhieuThuByMaSV_Result> sp_GetPhieuThuByMaSV(string masv)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPhieuThuByMaSV_Result>("sp_GetPhieuThuByMaSV", masvParameter);
        }
    
        public virtual ObjectResult<sp_GetPhieuThuByMasvAndSoPhieu_Result> sp_GetPhieuThuByMasvAndSoPhieu(string masv, string sophieu)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            var sophieuParameter = sophieu != null ?
                new ObjectParameter("sophieu", sophieu) :
                new ObjectParameter("sophieu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPhieuThuByMasvAndSoPhieu_Result>("sp_GetPhieuThuByMasvAndSoPhieu", masvParameter, sophieuParameter);
        }
    
        public virtual ObjectResult<sp_GetPhieuThuByNgayThanhToan_Result> sp_GetPhieuThuByNgayThanhToan(Nullable<System.DateTime> ngaybatdau, Nullable<System.DateTime> ngayketthuc)
        {
            var ngaybatdauParameter = ngaybatdau.HasValue ?
                new ObjectParameter("ngaybatdau", ngaybatdau) :
                new ObjectParameter("ngaybatdau", typeof(System.DateTime));
    
            var ngayketthucParameter = ngayketthuc.HasValue ?
                new ObjectParameter("ngayketthuc", ngayketthuc) :
                new ObjectParameter("ngayketthuc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPhieuThuByNgayThanhToan_Result>("sp_GetPhieuThuByNgayThanhToan", ngaybatdauParameter, ngayketthucParameter);
        }
    
        public virtual ObjectResult<sp_GetPhieuThuBySoPhieu_Result> sp_GetPhieuThuBySoPhieu(string sophieu)
        {
            var sophieuParameter = sophieu != null ?
                new ObjectParameter("sophieu", sophieu) :
                new ObjectParameter("sophieu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPhieuThuBySoPhieu_Result>("sp_GetPhieuThuBySoPhieu", sophieuParameter);
        }
    
        public virtual ObjectResult<sp_GetPhieuThuByTrangThai_Result> sp_GetPhieuThuByTrangThai(string trangthai)
        {
            var trangthaiParameter = trangthai != null ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetPhieuThuByTrangThai_Result>("sp_GetPhieuThuByTrangThai", trangthaiParameter);
        }
    
        public virtual ObjectResult<sp_GetSinhVien_Result> sp_GetSinhVien(string mssv, string matkhau)
        {
            var mssvParameter = mssv != null ?
                new ObjectParameter("mssv", mssv) :
                new ObjectParameter("mssv", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetSinhVien_Result>("sp_GetSinhVien", mssvParameter, matkhauParameter);
        }
    
        public virtual ObjectResult<string> sp_GetTenMonHocByMaMH(string mamh)
        {
            var mamhParameter = mamh != null ?
                new ObjectParameter("mamh", mamh) :
                new ObjectParameter("mamh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_GetTenMonHocByMaMH", mamhParameter);
        }
    
        public virtual ObjectResult<string> sp_GetTrangThai()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_GetTrangThai");
        }
    
        public virtual int sp_Insert_KhoanThu(string mamh, string tenmh, Nullable<int> sotc, Nullable<int> sotiet, Nullable<decimal> dongia)
        {
            var mamhParameter = mamh != null ?
                new ObjectParameter("Mamh", mamh) :
                new ObjectParameter("Mamh", typeof(string));
    
            var tenmhParameter = tenmh != null ?
                new ObjectParameter("Tenmh", tenmh) :
                new ObjectParameter("Tenmh", typeof(string));
    
            var sotcParameter = sotc.HasValue ?
                new ObjectParameter("Sotc", sotc) :
                new ObjectParameter("Sotc", typeof(int));
    
            var sotietParameter = sotiet.HasValue ?
                new ObjectParameter("Sotiet", sotiet) :
                new ObjectParameter("Sotiet", typeof(int));
    
            var dongiaParameter = dongia.HasValue ?
                new ObjectParameter("Dongia", dongia) :
                new ObjectParameter("Dongia", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Insert_KhoanThu", mamhParameter, tenmhParameter, sotcParameter, sotietParameter, dongiaParameter);
        }
    
        public virtual ObjectResult<sp_KhoanThu_Result> sp_KhoanThu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_KhoanThu_Result>("sp_KhoanThu");
        }
    
        public virtual ObjectResult<string> sp_SinhVien(string mssv, string matkhau)
        {
            var mssvParameter = mssv != null ?
                new ObjectParameter("Mssv", mssv) :
                new ObjectParameter("Mssv", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_SinhVien", mssvParameter, matkhauParameter);
        }
    
        public virtual ObjectResult<string> sp_TrangThai()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_TrangThai");
        }
    
        public virtual int sp_Update_KhoanThu(Nullable<int> id, string mamh, string tenmh, Nullable<int> sotc, Nullable<int> sotiet, Nullable<decimal> dongia)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var mamhParameter = mamh != null ?
                new ObjectParameter("Mamh", mamh) :
                new ObjectParameter("Mamh", typeof(string));
    
            var tenmhParameter = tenmh != null ?
                new ObjectParameter("Tenmh", tenmh) :
                new ObjectParameter("Tenmh", typeof(string));
    
            var sotcParameter = sotc.HasValue ?
                new ObjectParameter("Sotc", sotc) :
                new ObjectParameter("Sotc", typeof(int));
    
            var sotietParameter = sotiet.HasValue ?
                new ObjectParameter("Sotiet", sotiet) :
                new ObjectParameter("Sotiet", typeof(int));
    
            var dongiaParameter = dongia.HasValue ?
                new ObjectParameter("Dongia", dongia) :
                new ObjectParameter("Dongia", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Update_KhoanThu", idParameter, mamhParameter, tenmhParameter, sotcParameter, sotietParameter, dongiaParameter);
        }
    
        public virtual ObjectResult<TBL_SinhVien> sp_Get_SinhVien(string mssv, string matkhau)
        {
            var mssvParameter = mssv != null ?
                new ObjectParameter("mssv", mssv) :
                new ObjectParameter("mssv", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TBL_SinhVien>("sp_Get_SinhVien", mssvParameter, matkhauParameter);
        }
    
        public virtual ObjectResult<TBL_SinhVien> sp_Get_SinhVien(string mssv, string matkhau, MergeOption mergeOption)
        {
            var mssvParameter = mssv != null ?
                new ObjectParameter("mssv", mssv) :
                new ObjectParameter("mssv", typeof(string));
    
            var matkhauParameter = matkhau != null ?
                new ObjectParameter("matkhau", matkhau) :
                new ObjectParameter("matkhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TBL_SinhVien>("sp_Get_SinhVien", mergeOption, mssvParameter, matkhauParameter);
        }
    
        public virtual ObjectResult<string> sp_Get_EmailSinhVien(string mssv)
        {
            var mssvParameter = mssv != null ?
                new ObjectParameter("mssv", mssv) :
                new ObjectParameter("mssv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_Get_EmailSinhVien", mssvParameter);
        }
    
        public virtual ObjectResult<TBL_ChiTietPhieuThu> sp_Get_ChiTietPhieuThu(string soPhieu)
        {
            var soPhieuParameter = soPhieu != null ?
                new ObjectParameter("soPhieu", soPhieu) :
                new ObjectParameter("soPhieu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TBL_ChiTietPhieuThu>("sp_Get_ChiTietPhieuThu", soPhieuParameter);
        }
    
        public virtual ObjectResult<TBL_ChiTietPhieuThu> sp_Get_ChiTietPhieuThu(string soPhieu, MergeOption mergeOption)
        {
            var soPhieuParameter = soPhieu != null ?
                new ObjectParameter("soPhieu", soPhieu) :
                new ObjectParameter("soPhieu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TBL_ChiTietPhieuThu>("sp_Get_ChiTietPhieuThu", mergeOption, soPhieuParameter);
        }
    
        public virtual ObjectResult<string> sp_Get_TenMonHocByMaMH(string mamh)
        {
            var mamhParameter = mamh != null ?
                new ObjectParameter("mamh", mamh) :
                new ObjectParameter("mamh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_Get_TenMonHocByMaMH", mamhParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_Get_DonGiaByMaMH(string mamh)
        {
            var mamhParameter = mamh != null ?
                new ObjectParameter("mamh", mamh) :
                new ObjectParameter("mamh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_Get_DonGiaByMaMH", mamhParameter);
        }
    
        public virtual ObjectResult<TBL_PhieuThu> sp_GetAllPhieu_Thu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TBL_PhieuThu>("sp_GetAllPhieu_Thu");
        }
    
        public virtual ObjectResult<TBL_PhieuThu> sp_GetAllPhieu_Thu(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TBL_PhieuThu>("sp_GetAllPhieu_Thu", mergeOption);
        }
    
        public virtual ObjectResult<string> sp_Get_TrangThai()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_Get_TrangThai");
        }
    
        public virtual ObjectResult<TBL_PhieuThu> sp_Get_PhieuThuByMaSV(string masv)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TBL_PhieuThu>("sp_Get_PhieuThuByMaSV", masvParameter);
        }
    
        public virtual ObjectResult<TBL_PhieuThu> sp_Get_PhieuThuByMaSV(string masv, MergeOption mergeOption)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TBL_PhieuThu>("sp_Get_PhieuThuByMaSV", mergeOption, masvParameter);
        }
    
        public virtual ObjectResult<TBL_PhieuThu> sp_Get_PhieuThuBySoPhieu(string sophieu)
        {
            var sophieuParameter = sophieu != null ?
                new ObjectParameter("sophieu", sophieu) :
                new ObjectParameter("sophieu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TBL_PhieuThu>("sp_Get_PhieuThuBySoPhieu", sophieuParameter);
        }
    
        public virtual ObjectResult<TBL_PhieuThu> sp_Get_PhieuThuBySoPhieu(string sophieu, MergeOption mergeOption)
        {
            var sophieuParameter = sophieu != null ?
                new ObjectParameter("sophieu", sophieu) :
                new ObjectParameter("sophieu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TBL_PhieuThu>("sp_Get_PhieuThuBySoPhieu", mergeOption, sophieuParameter);
        }
    
        public virtual ObjectResult<TBL_PhieuThu> sp_Get_PhieuThuByNgayThanhToan(Nullable<System.DateTime> ngaybatdau, Nullable<System.DateTime> ngayketthuc)
        {
            var ngaybatdauParameter = ngaybatdau.HasValue ?
                new ObjectParameter("ngaybatdau", ngaybatdau) :
                new ObjectParameter("ngaybatdau", typeof(System.DateTime));
    
            var ngayketthucParameter = ngayketthuc.HasValue ?
                new ObjectParameter("ngayketthuc", ngayketthuc) :
                new ObjectParameter("ngayketthuc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TBL_PhieuThu>("sp_Get_PhieuThuByNgayThanhToan", ngaybatdauParameter, ngayketthucParameter);
        }
    
        public virtual ObjectResult<TBL_PhieuThu> sp_Get_PhieuThuByNgayThanhToan(Nullable<System.DateTime> ngaybatdau, Nullable<System.DateTime> ngayketthuc, MergeOption mergeOption)
        {
            var ngaybatdauParameter = ngaybatdau.HasValue ?
                new ObjectParameter("ngaybatdau", ngaybatdau) :
                new ObjectParameter("ngaybatdau", typeof(System.DateTime));
    
            var ngayketthucParameter = ngayketthuc.HasValue ?
                new ObjectParameter("ngayketthuc", ngayketthuc) :
                new ObjectParameter("ngayketthuc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TBL_PhieuThu>("sp_Get_PhieuThuByNgayThanhToan", mergeOption, ngaybatdauParameter, ngayketthucParameter);
        }
    
        public virtual ObjectResult<TBL_PhieuThu> sp_Get_PhieuThuByMasvAndSoPhieu(string masv, string sophieu)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            var sophieuParameter = sophieu != null ?
                new ObjectParameter("sophieu", sophieu) :
                new ObjectParameter("sophieu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TBL_PhieuThu>("sp_Get_PhieuThuByMasvAndSoPhieu", masvParameter, sophieuParameter);
        }
    
        public virtual ObjectResult<TBL_PhieuThu> sp_Get_PhieuThuByMasvAndSoPhieu(string masv, string sophieu, MergeOption mergeOption)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            var sophieuParameter = sophieu != null ?
                new ObjectParameter("sophieu", sophieu) :
                new ObjectParameter("sophieu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TBL_PhieuThu>("sp_Get_PhieuThuByMasvAndSoPhieu", mergeOption, masvParameter, sophieuParameter);
        }
    
        public virtual ObjectResult<TBL_PhieuThu> sp_Get_PhieuThuByAll(string masv, string sophieu, Nullable<System.DateTime> ngaybatdau, Nullable<System.DateTime> ngayketthuc)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            var sophieuParameter = sophieu != null ?
                new ObjectParameter("sophieu", sophieu) :
                new ObjectParameter("sophieu", typeof(string));
    
            var ngaybatdauParameter = ngaybatdau.HasValue ?
                new ObjectParameter("ngaybatdau", ngaybatdau) :
                new ObjectParameter("ngaybatdau", typeof(System.DateTime));
    
            var ngayketthucParameter = ngayketthuc.HasValue ?
                new ObjectParameter("ngayketthuc", ngayketthuc) :
                new ObjectParameter("ngayketthuc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TBL_PhieuThu>("sp_Get_PhieuThuByAll", masvParameter, sophieuParameter, ngaybatdauParameter, ngayketthucParameter);
        }
    
        public virtual ObjectResult<TBL_PhieuThu> sp_Get_PhieuThuByAll(string masv, string sophieu, Nullable<System.DateTime> ngaybatdau, Nullable<System.DateTime> ngayketthuc, MergeOption mergeOption)
        {
            var masvParameter = masv != null ?
                new ObjectParameter("masv", masv) :
                new ObjectParameter("masv", typeof(string));
    
            var sophieuParameter = sophieu != null ?
                new ObjectParameter("sophieu", sophieu) :
                new ObjectParameter("sophieu", typeof(string));
    
            var ngaybatdauParameter = ngaybatdau.HasValue ?
                new ObjectParameter("ngaybatdau", ngaybatdau) :
                new ObjectParameter("ngaybatdau", typeof(System.DateTime));
    
            var ngayketthucParameter = ngayketthuc.HasValue ?
                new ObjectParameter("ngayketthuc", ngayketthuc) :
                new ObjectParameter("ngayketthuc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TBL_PhieuThu>("sp_Get_PhieuThuByAll", mergeOption, masvParameter, sophieuParameter, ngaybatdauParameter, ngayketthucParameter);
        }
    
        public virtual ObjectResult<TBL_PhieuThu> sp_Get_PhieuThuByTrangThai(string trangthai)
        {
            var trangthaiParameter = trangthai != null ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TBL_PhieuThu>("sp_Get_PhieuThuByTrangThai", trangthaiParameter);
        }
    
        public virtual ObjectResult<TBL_PhieuThu> sp_Get_PhieuThuByTrangThai(string trangthai, MergeOption mergeOption)
        {
            var trangthaiParameter = trangthai != null ?
                new ObjectParameter("trangthai", trangthai) :
                new ObjectParameter("trangthai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TBL_PhieuThu>("sp_Get_PhieuThuByTrangThai", mergeOption, trangthaiParameter);
        }
    }
}
