//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnThucTap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SinhVien
    {
        public TBL_SinhVien()
        {
            this.TBL_PhieuThu = new HashSet<TBL_PhieuThu>();
        }
    
        public string Mssv { get; set; }
        public string Hoten { get; set; }
        public string Gioitinh { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public string Lophoc { get; set; }
        public string Mail { get; set; }
        public string MatKhau { get; set; }
    
        public virtual ICollection<TBL_PhieuThu> TBL_PhieuThu { get; set; }
    }
}
